import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — CompDataVault",
};

// NOTE: this is a first-pass draft, not attorney-reviewed. Every
// [INSERT ...] placeholder below needs a real value, and legal counsel
// should sign off before this is treated as binding. See the delivery
// notes from the drafting session for the full list of open items
// (entity name, governing state, DMCA agent, pricing terms, notice
// periods, state-specific consumer-protection disclosures).
const SECTIONS: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "1. Description of the Service",
    paragraphs: [
      "CompDataVault is a software platform that allows commercial real estate professionals to upload, store, organize, search, and analyze property comparable (“comp”) data, including data extracted from marketing flyers and other documents submitted by the User. The Service includes features such as automated data extraction, saved searches, valuation estimates, mapping, and data export.",
    ],
  },
  {
    heading: "2. Eligibility and Accounts",
    paragraphs: [
      "You must be at least 18 years old and capable of forming a binding contract to use the Service.",
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
      "You agree to provide accurate account information and to keep it current.",
      "You may not share your account with others or allow unauthorized third parties to access the Service through your account, except through features we explicitly provide for that purpose (e.g., authorized-sender email forwarding).",
    ],
  },
  {
    heading: "3. User Content",
    paragraphs: [
      "“User Content” means any document, flyer, file, image, email, text, or data that you upload, forward, or otherwise submit to the Service.",
      "You represent and warrant that you own the User Content you submit, or have all necessary rights, licenses, and permissions to submit it and to store, process, and extract data from it as contemplated by these Terms; and that your use of the Service, including any User Content you submit, does not infringe, misappropriate, or violate any third party's intellectual property rights, privacy rights, or any applicable law.",
      "You grant CompDataVault a limited, non-exclusive, worldwide, royalty-free license to host, store, reproduce, process, and display your User Content solely as necessary to provide and improve the Service to you. We do not claim ownership of your User Content.",
      "You agree not to upload or submit content that infringes any copyright, trademark, trade secret, or other proprietary right of any third party; that you do not have the legal right to store or distribute, including bulk collections of third-party marketing materials obtained without authorization; that contains malicious code or is submitted to disrupt the Service; or that is unlawful, fraudulent, or misleading.",
      "We reserve the right, but have no obligation, to remove User Content that we reasonably believe violates these Terms or applicable law.",
    ],
  },
  {
    heading: "4. Acceptable Use",
    paragraphs: [
      "You agree not to: scrape, harvest, or bulk-collect data or documents from third-party websites or services in violation of those services' terms; attempt to gain unauthorized access to another user's account, vault, or data; reverse-engineer or decompile the Service except as permitted by law; use automated means to access the Service in a manner that burdens our infrastructure beyond normal human use; resell or sublicense the Service without our written consent; or use the Service in violation of any applicable law.",
    ],
  },
  {
    heading: "5. Third-Party Data, Services, and Estimates",
    paragraphs: [
      "The Service uses third-party infrastructure to provide certain features, including geocoding, mapping, and email routing. We are not responsible for the availability, accuracy, or performance of these third-party services.",
      "Valuation and analysis features are not professional advice. Any valuation estimate, price-per-square-foot range, market comparison, or similar analytical output generated by the Service is calculated automatically from the data in your vault and is provided for informational purposes only. It is not an appraisal, does not constitute financial, investment, legal, or professional real estate advice, and should not be relied upon as the sole basis for any transaction or decision. Consult a licensed appraiser, broker, attorney, or other qualified professional before making decisions based on Service output.",
      "We do not guarantee the accuracy, completeness, or currency of any data extracted from uploaded documents, whether extracted automatically or entered manually. You are responsible for independently verifying any data before relying on it.",
    ],
  },
  {
    heading: "6. Subscription, Fees, and Billing",
    paragraphs: [
      "Certain features of the Service require a paid subscription. Current pricing is available at [INSERT PRICING PAGE URL]. Subscriptions renew automatically for successive billing periods unless canceled prior to the renewal date. Fees are billed in advance and are non-refundable except as required by law or as expressly stated in these Terms.",
      "We may change subscription pricing with at least [INSERT NOTICE PERIOD] advance notice. Continued use of the Service after a price change takes effect constitutes acceptance of the new pricing.",
      "You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the then-current billing period; no partial-period refunds will be issued except as required by law. Failure to pay applicable fees may result in suspension or termination of your account.",
    ],
  },
  {
    heading: "7. Intellectual Property",
    paragraphs: [
      "The Service, including its software, design, and underlying technology (but excluding User Content), is owned by CompDataVault and its licensors and is protected by intellectual property laws. Nothing in these Terms grants you any right to use our trademarks, logos, or branding without prior written consent.",
    ],
  },
  {
    heading: "8. Copyright Complaints (DMCA)",
    paragraphs: [
      "CompDataVault respects the intellectual property rights of others and expects Users to do the same. If you believe content stored on the Service infringes your copyright, you may submit a notice to our designated agent containing a physical or electronic signature of the copyright owner or authorized representative; identification of the copyrighted work claimed to be infringed; identification of the material claimed to be infringing, with information reasonably sufficient to locate it; your contact information; a statement that you have a good-faith belief the use is not authorized by the copyright owner, its agent, or the law; and a statement, made under penalty of perjury, that the information in the notice is accurate and that you are authorized to act on behalf of the copyright owner.",
      "Designated Agent: [INSERT NAME], [INSERT ADDRESS], [INSERT EMAIL]. (Registration with the U.S. Copyright Office pending.)",
      "We will respond to properly submitted notices in accordance with the Digital Millennium Copyright Act, which may include removing or disabling access to the identified content and, in appropriate cases, terminating accounts of repeat infringers. A User who believes their content was removed in error may submit a counter-notice consistent with DMCA requirements.",
    ],
  },
  {
    heading: "9. Privacy",
    paragraphs: [
      "Our collection and use of personal information in connection with the Service is described in our Privacy Policy, which is incorporated into these Terms by reference.",
    ],
  },
  {
    heading: "10. Disclaimers",
    paragraphs: [
      "THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE,” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. WE DO NOT WARRANT THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY DATA EXTRACTED, STORED, OR GENERATED BY THE SERVICE.",
    ],
  },
  {
    heading: "11. Limitation of Liability",
    paragraphs: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPDATAVAULT AND ITS OFFICERS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, BUSINESS, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the above limitations may not apply to you.",
    ],
  },
  {
    heading: "12. Indemnification",
    paragraphs: [
      "You agree to indemnify and hold harmless CompDataVault and its officers, employees, and affiliates from any claims, damages, losses, and expenses (including reasonable attorneys' fees) arising out of your User Content, your violation of these Terms, or your violation of any third-party right, including intellectual property rights.",
    ],
  },
  {
    heading: "13. Termination",
    paragraphs: [
      "You may terminate your account at any time through account settings or by contacting support. We may suspend or terminate your access to the Service if you violate these Terms, fail to pay applicable fees, or for any other reason with reasonable notice, except that we may suspend access immediately where we reasonably believe it necessary to prevent harm to the Service, other users, or third parties.",
      "Upon termination, your right to use the Service ceases immediately. Sections of these Terms that by their nature should survive termination (including User Content warranties, DMCA, Disclaimers, Limitation of Liability, and Indemnification) will survive.",
    ],
  },
  {
    heading: "14. Modifications to the Service and Terms",
    paragraphs: [
      "We may modify the Service or these Terms at any time. Material changes to these Terms will be communicated in advance of taking effect. Continued use of the Service after changes take effect constitutes acceptance.",
    ],
  },
  {
    heading: "15. Governing Law and Dispute Resolution",
    paragraphs: [
      "These Terms are governed by the laws of the State of [INSERT STATE], without regard to conflict-of-law principles.",
    ],
  },
  {
    heading: "16. Miscellaneous",
    paragraphs: [
      "These Terms constitute the entire agreement between you and CompDataVault regarding the Service and supersede any prior agreements. If any provision is found unenforceable, the remaining provisions remain in full effect. Our failure to enforce any provision is not a waiver of our right to do so later. You may not assign these Terms without our prior written consent; we may assign these Terms in connection with a merger, acquisition, or sale of assets.",
    ],
  },
  {
    heading: "17. Contact",
    paragraphs: ["Questions about these Terms can be directed to [INSERT CONTACT EMAIL]."],
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="font-serif text-3xl font-bold tracking-tight">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-dim">
        Effective Date: [INSERT DATE] &middot; Last Updated: [INSERT DATE]
      </p>
      <p className="mt-6 border border-line bg-accent/[0.03] px-4 py-3 text-sm text-dim">
        Draft under legal review &mdash; not yet finalized.
      </p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-foreground">
        {SECTIONS.map((section) => (
          <section key={section.heading}>
            <h2 className="font-serif text-lg font-semibold">
              {section.heading}
            </h2>
            {section.paragraphs.map((p, i) => (
              <p key={i} className="mt-3 text-dim">
                {p}
              </p>
            ))}
          </section>
        ))}
      </div>
    </div>
  );
}
